#+TITLE:       被洗脑的爱国者
#+AUTHOR:      venmos
#+EMAIL:       venmos@fuck.gfw.es
#+DATE:        2012-09-21
#+URI:         /blog/%y/%m/%d/china-sb
#+KEYWORDS:    被, 洗脑, 爱国
#+TAGS:        venmos,
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 被, 洗脑, 爱国

2012年9月15日，大陆各地民众自发上街，用实际行动向香港人展示国民洗脑教育的危害。

王朔: 一些连街边小偷都不敢呵斥的人，却勇于高呼”灭了小日本”。 一帮连活着的人民的痛苦都漠不关心的人，却有脸说不忘死去的同胞。 有那么一群人，在日本叫法西斯，在德国叫纳粹，在中国叫爱国者。

熊培云: 通过攻击邻居和路人给遥远敌人致命一击，这是爱国者的伟大发明。 在很多人那里，爱国主义只是一种致幻剂，当它被唤起，那一刻即使一个最无权无势的人也会自以为是国家的主人。更何况爱国还能让他们理直气壮伤害他人，做几日无法无天的统治者。我不反对他人爱国，但我坚决反对任何人以爱国的名义戗害同胞。

当宝宝喝下毒奶时，你们没有抗议；当官员强奸幼女时，你们没有抗议；当孩子们被掩埋时，你们没有抗议；当裸官携款潜逃时，你们没有抗议；当子弹射向学生时，你们没有抗议；当得令”奉旨爱国”时，你们像打了鸡血般兴奋，将拳头和棍棒伸向了身边的同胞。就算是在动物世界，都找不出像你们这样的贱货！

侵吞中国领土最多的是俄罗斯，第二是印度，其次哈萨克斯坦，缅甸，越南，塔吉克，吉尔吉斯斯坦，朝鲜，菲律宾。把日本拿上显著位置上来说，是因为政治因素――日本最易引起国民反感，容易激发愤青热血沸腾。 而一说到俄罗斯，所有爱国者和愤青们都顷刻鸦雀无声，连屁也不敢放一个。

砸日本车烧日本旗抵制日货的人，和围攻美国领事馆的利比亚暴徒其实是一种人，程度有差，性质无异。 他们从生下就被洗脑，失去了自由的思想、独立的人格和美好的情怀，大脑和灵魂空洞，不懂得爱和喜欢，却自认有崇高信仰。 他们潜伏在我们周围，在需要的时候被恶魔召唤，他们不是蠢货，是爱国主义僵尸。

慕容雪村: 中国人要想证明自己优于日本人，光凭愤怒和狂吼是不够的，还应拥有文明的力量。与其喊破嗓子去抵制日货，不如想想怎样才能造出更优质的产品。与其动不动就去操日本人的妈，不如想想怎样才能比日本人更文明、更令人尊敬。就算真要抗日，我也希望中国人能用头脑、用文明来抵抗，而不是只会用愤怒的四肢。

法学家卡尔・施密特有句名言: “政治就是划分敌我”。 对于一个政治运动大国，需要持续地制造敌人。爱国主义、民族主义不过是牵系愚民的狗链。最终维护的，就是一组妄图永恒运作的集权机器。

任志强: 一群流氓以中国同胞的名义为打砸抢烧的行为辨护。抗战时当伪军，皇协军，汉奸的也都是中国人。别以为是中国人就可以欺负中国人。别以为是国人就可以侵犯国人的财产权利。别以为是中国人就可以践踏中国的法律。在中国打砸抢烧国人合法的财产不能证明这是爱国。只能证明你们是卖国，出卖国人的灵魂。

张泉灵: 说句实话，我以前真不相信这社会隐藏着这么多流氓和脑残。是我幼稚了。 （大批网友回复张泉灵: 贵台功不可没）

[[http://lh5.googleusercontent.com/NE40jU8eRm4JnP4Gb5CoZlWetsqmzyKd3erirScTHT1-IpwzZrUjoSeLqP_EHR7uNJwA5X88_Jzel4xUdAS-ucrY5kjLEelAYxyT-JNVw94-ZsRtaNc]]
