#+TITLE:       Org-Mode Org-Remember
#+AUTHOR:      venmos
#+EMAIL:       venmos@fuck.gfw.es
#+DATE:        2012-09-02
#+URI:         /blog/%y/%m/%d/emacs-plugin-org-mode-org-remember
#+KEYWORDS:    emacs, org-mode, org-remember
#+TAGS:        emacs,
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: emacs, org-mode, org-remember

最早我是使用Evernote来记录各种笔记和资料,后来因为Evernote的速度巨慢,资料录入一旦太多就卡的不能行,最主要的是Evernote排版功能太2了.于是就转向了Simplenote,Simplenote是纯文本,且支持Markdown,开放API,在各种操作系统下(甚至包括Vim与Emacs)都有相应的客户端支持.但是用了一段时间以后也发现一些问题,比如频繁修改多个资料会同步出多个同名文件,比如由于GAE被GFW了,每次都要用代理,速度缓慢等等.后来我将目光转向了VimWiki,使用了很长一段时间感觉非常不错!VimWiki有非常强大的排版与Wiki功能,而且可以整站输出.HTML文件,搭配我自己自定义的.CSS,输出后自动Rsync到服务器上.这样在外我使用手机游览器也可以查阅游览了(PS:不能修改).而随着我抛弃Vim转向Emacs之后,自而而然的我的笔记系统就从VimWiki转向了Org-Mode.

Org-Mode是Emacs最著名的Lisp扩展之一,网上各种介绍多如牛毛,我就不罗嗦了.听说很多Vimer逃向Emacs就是为了使用Org-Mode,这就足以证明它的强大.在最新的Emacs24版本里已经集成了Org-Mode.

凡是读过GTD系列文章或者书籍的童鞋就应该知道Index,Index是GTD里非常重要的一个组成部分,GTD对于Index的定义就是用来收集材料的工具,且使用时不需要另外思考.比如,我在做一件工作时,领导突然又给我分配一件明天的工作.此时我只需要在Index里记录下来这件事,然后立刻返回到我之前被打断的工作中去.在这个过程里,我往Index里录入的只是这件事,我不需要思考何时开始这件事,如何开始?如何完成?只是简单的记录,这不会打断我之前工作时的思路.在我完成上一件工作之后,我在返回查看Index,将之前草记的内容加上TAG、时间等进行细化分类,方便以后查阅.

虽然我是个瘾科技,但是我还是认为最好的Index工具是Moleskine(笑).而在Org-Mode里,org-remember是非常好用的Index工具.在我使用Emacs编程、编辑文件、修改软件配置时,突然有了神码灵感、想法、或者要做的事情时,我都会一个快捷键唤出org-remember,然后迅速录入,在一个快捷键保存+关闭org-remember,这是一件多么惬意的事情.

重度使用org-remember之后,又出现了一个新的问题.那就是我每天的想法和事情可能太多,而org-remember默认是全部都保存在一个文件之中的(默认是~/.note).每天回家一打开.Note(我使用Dropbox来同步我的Org目录)就会发现乱七八糟杂七杂八的东西一大堆挤压在一起,我通常每天晚上都要花费一些精力才能将.Note之中的各种笔记、想法、TODO分门别类的加上标签,修改格式排版等等之后在耐心的一个一个的剪贴粘贴到我的其他Org文件之中.一开始的几天还能忍受,觉得这是一种良好的习惯,可以帮我回顾一天的总结并加深印象.但是随着日子的增加,难免觉得这是一种折磨,因为录入.Note之中的各种东西都是没有分类的,都只是一些文字的片段,在查阅的时候我往往要思考许久才能从脑海之中搜索出来这件事是和什么相关的,然后才能在给它定义类别.难道就没有一种办法可以让org-remember自己知道录入的什么,而进行自动整理吗?

答案是有的,那就是自定义org-remember-templates.

通过自定义org-remember-templates,我们可以在唤出org-remember时通过几个简单的快捷键告知org-remember我所录入的信息的大体类别,之后保存时org-remember就会根据我所自定义的模板默认的将信息保存进其中分类的Org文件之中.

一个简单的org-remember-templates如下,其中我只定义了两个类别:TODO与Note,分别指向两个Org文件:todo.org与note.org.TODO用来记录各种要做的事情,Note用来记录笔记或者灵感.当然你也可以按照自己的想法自定义,这里只是一个演示:

#+begin_src
(global-set-key "\C-cr" 'org-remember)
(org-remember-insinuate)
(setq org-default-notes-file "~/.emacs.d/.notes.org")
(setq org-remember-templates
    '(("TODO" ?t "* TODO %?\n %x\n %a" "~/.emacs.d/org/todo.org" "Index")
  ("Note" ?n "* Note %?\n %x\n %a" "~/.emacs.d/org/note.org" "Note")
  ))
#+end_src

将上面的代码插入你的.emacs之后重启Emacs,再次唤出org-remember(我绑定了一个快捷键是C-c r)时会发现多了两个选项,(t)odo和(n)ote.当你按快捷键t时,org-remember就会自动转唤出一个TODO,在录入完内容之后按快捷键C-c C-c保存时,其会自动保存到~/.emacs.d/org/todo.org文件的Index项之下,同时也会记录下我是在编辑哪个文件时唤出的org-remember.同理,如果按n换出Note模式,则其会保存到~/.emacs.d/org/note.org文件中的Note项之下.


如此,通过自定义org-remember-templates,就可以让org-remember根据个人自定义的习惯分门别类的储存临时信息,在需要整理的时候减轻了非常多的工作量.当然这只是Org-Mode强大功能之中的一个小角,看样子以后我还有很长的学习路要走…:)
