#+TITLE:       Emacs 快速切换光标位置与窗口
#+AUTHOR:      venmos
#+EMAIL:       venmos@fuck.gfw.es
#+DATE:        2013-07-08
#+URI:         /blog/%y/%m/%d/emacs-ace-jump-switch-windows
#+KEYWORDS:    emacs, 快速, 切换, 光标, 窗口
#+TAGS:        emacs,
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: emacs, 快速, 切换, 光标, 窗口

Emacs的光标移动能力估计是最被人所诟病的地方之一了，不过通过强大的Ace-Jump-Mode扩展，Emacs也能做到像Vim那样的快速移动光标的能力，甚至做的更好。

- Ace-Jump-Mode的官方演示地址 => http://dl.dropboxusercontent.com/u/3254819/AceJumpModeDemo/AceJumpDemo.htm
- Ace-Jump-Mode的Github => https://github.com/winterTTr/ace-jump-mode

使用el-get就可以安装Ace-Jump-Mode，然后添加以下配置文件

#+begin_src
;;
;; ace jump mode major function
;; 
(autoload
  'ace-jump-mode
  "ace-jump-mode"
  "Emacs quick move minor mode"
  t)
;; you can select the key you prefer to
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)

;; 
;; enable a more powerful jump back function from ace jump mode
;;
(autoload
  'ace-jump-mode-pop-mark
  "ace-jump-mode"
  "Ace jump back:-)"
  t)
(eval-after-load "ace-jump-mode"
  '(ace-jump-mode-enable-mark-sync))
(define-key global-map (kbd "C-x SPC") 'ace-jump-mode-pop-mark)

;;If you use viper mode :
(define-key viper-vi-global-user-map (kbd "SPC") 'ace-jump-mode)
;;If you use evil
(define-key evil-normal-state-map (kbd "SPC") 'ace-jump-mode)
#+end_src

Ace-Jump-Mode提供三种跳跃方式：


- “C-c SPC” ==> ace-jump-word-mode

enter first character of a word, select the highlighted key to move to it.

- “C-u C-c SPC” ==> ace-jump-char-mode

enter a character for query, select the highlighted key to move to it.

- “C-u C-u C-c SPC” ==> ace-jump-line-mode

each non-empty line will be marked, select the highlighted key to move to it.


具体使用就是，输入以上三种中任意之一的快捷键，MiniBuffer就会提示你输入一个字母，比如你想跳到World这个单词，就输入W。之后Ace-Jump-Mode会将文件中所有W打头的单词显示为一个单个字母，然后你在按这个字母就会跳到那个单词的开头了。语言比较难解释，所以最好还是看作者制作的说明动画，一看就能明白了。

估计大家都知道Emacs能分割出很多个窗口，这样能在某些方面可以极大的提高效率。如果我分出两个窗口，可以使用C-x o来从两个窗口中快捷的切换，但是如果我分割的窗口多于三个，在用C-x o来切换就很蛋疼了。如果你跟我一样经常使用三个以上的窗口分割，那么你也需要Switch-Windows这个扩展包。它唯一的功能就是：当你的分割窗口大于等于三的时候，在你按下C-x o时，会自动的在所有的分割窗口上显示一个数字，然后你在按下这个数字键就会快速的跳跃到这个窗口了。

这个扩展包比较简单，用el-get安装的话，默认什么配置都不需要就可以使用了。

- Switch-Windows的Github => https://github.com/dimitri/switch-window
