#+TITLE:       PSV Sony 的未来？
#+AUTHOR:      venmos
#+EMAIL:       venmos@fuck.gfw.es
#+DATE:        2012-07-08
#+URI:         /blog/%y/%m/%d/psv-sony-future
#+KEYWORDS:    psv, sony, 未来
#+TAGS:        acg,
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: psv, sony, 未来

昨天去外地出差，顺手买了一PSV。从使用了一下午的感觉来看，PSV就是一台披着游戏机外衣的平板电脑。感觉Sony在PSV上是下了血本了，甚至超越了自家的Android手机。莫名的有点PSV就是Sony的未来的感觉，甚至为它推出了PSS开发套件，这是明摆着的明修栈道暗度陈仓，司马昭之心人尽皆知…

众所周知，Sony目前已经落入前有狼后有虎的危险境地了。PC业务受全球行业衰退影响持续亏损，家电业务也萎靡不振，手机和平板业务沦为Google的“出版商”，唯一仍有些“霸权”的游戏机业务现在也在被iOS的不断强大、任天堂的的鬼点子倍多而倍受打压，随时都有可能被打下多年辛苦打拼而得来的“霸权”地位。

Sony若想继续生存，必然需要绝地反击。可惜的是Sony现在手中并没有那张可以打出绝地反击的王牌。跟所有日系IT企业一样，Sony发家时的迅速崛起靠的是超绝的硬件设计，细致入微的做工，超越时代的功能。但软肋也同所有的日系企业一样，缺乏自主的消费级系统软件，没有自己的完善的软件生态链。所以自全球进入信息大爆炸时代起，没有自主软生态圈的Sony和其他日系IT企业一样，就只能一步步沦为它人争夺地盘的棋子了。

可能有童鞋说Sony刚收购了Sony Ericsson剩余的股份，现在自家有完整的手机业务，还有开源的Android。问题是，不管Android有多开源（实际上不？），功能多强大，毕竟不是Sony自家的孩子，不能根据自己的未来随心所欲的扩展，始终要看Google的脸色，更何况Google近几年是年年打破系统开发商的禁忌，不断的推出自有品牌的硬件产品，着实伤了这些在Android诞生之初便开始为Android的生存拼尽全力的“老臣”们的心。

如果在Android的基础上进行大量定制性开发，则等价于抛弃了已有的广大的Android生态圈，如刚发布的Sony Tablet P； 如不进行大量的定执行开发，只能是放下身价与三星之流上演“同门相残”的好戏，岂不是伤了曾经的个人电子消费业巨头的脸面？；

所以，无论Android发展势头如何的好，其最好的结局也只能落得当年给微软当“出版商”的时期相同而已。

内部没有王牌，外部的牌靠不住，那就只能卖了裤子自立门户自力更生了。

自从PSP1000时代起就有关于Sony下一代掌机的传说，可惜玩家的年年等待只不过是等来了一代又一代的换汤不换药。终于有一天PSP后面不用再加4位数字了，可惜迎来的也只是一位被阉割了UMD的PSP… 我不禁猜想，对于曾经杀出重围坐上电玩业霸主位置的Sony，对于曾经的个人电子消费业全种类制衡的王者Sony来说，开发一款替代PSP的下一代掌机究竟有多么困难？究竟是哪里困难重重，直到今天才见天日？

So，在今天这个曾经的手机业巨头诺基亚轻松被干翻，iOS与Android二分天下（我似乎忘记了一个叫黑莓的东西？），且微软也磨刀霍霍随时准备全力血拼的移动手机市场靠自己的软硬件实力杀出一条血路，根本不现实。 So，在今天全球市场不断持续萎靡，云概念越炒越热，MacOS与Windows、Linux三分天下的个人计算机业靠自己的软硬件实力杀出一条血路？也根本不现实。 So，那就只能在自己目前尚且制霸的行业里靠自己的软硬件实力，明修栈道暗度陈仓来杀出一条血路了！

为什么在现在几乎人手一部移动智能化设备的时期要推出一款能搭载无数应用潜能的游戏机设备？ 为什么在连Win8都要搭载App Store的时期要在一款游戏机设备上搭载一家App Store? 为什么要为一台游戏机设备推出一套完整且免费的开发环境？

对于Sony来说优先于竞争对手抢先推出下一代掌机来维持霸主地位，难道不是最重要的吗？ 对于Sony来说，游戏机系统应当尽量精简来将更多的硬件资源供给游戏来展示出超越其他iOS/Android设备的精美画面，难道不是最重要的吗？ 对于Sony来说，抛弃种种不想关的硬件和开发多余功能的经费来尽量压低自己掌机的价格，难道不是最重要的吗？

难道PSV的种种紧紧是因为现在的人喜欢多功能的设备？难道他们在携带PSV的时候就不会携带iOS/Android？

真相就是PSV的操作系统无论从界面布局上，多应用后台切换上，操作习惯上，集成多种热门社交软件上，甚至是前置摄像头外加3G上都能看出PSV是一台彻头彻尾的披着游戏机外皮的平板！

既然其他市场上有拼不过的敌人，那就干脆依托自己最强力的消费受众群体来带大PSV的基数好了。PSV的基数越大，就会有越多的私人开发者投入其中，就像他们为iOS/Android所作的那样。随着PSV应用的私人/商业开发者越来越多，应用软件越来越多，总有一天它的基数可以将PSV System带向Sony的手机，平板，甚至笔记本电脑和电视机！

那时就是Sony抛弃Android，从此不用在看Google脸色之时。那时就是Sony拥有能插入iOS生态圈心脏的利剑，开始绝地反攻之时。
