#+TITLE:       树莓派 2 安装配置 Ubuntu Mate
#+AUTHOR:      venmos
#+EMAIL:       venmos@fuck.gfw.es
#+DATE:        2015-08-20 Thu
#+URI:         /blog/%y/%m/%d/raspberry2-install-ubuntu-mate1
#+KEYWORDS:    raspberry, ubuntu, 配置,
#+TAGS:        raspi, linux,
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 树莓派 2 安装配置 Ubuntu Mate.

Ubuntu Mate 是由 Ubuntu Gnome2 源代码派生出来的分支，由一群厌恶 Ubuntu 新 UI 和 Gnome3 激进的“创新”的人创建。

Ubuntu Mate 已经支持树莓派 2，它比树莓派官方的 Debian 拥有更多的软件包，更加易于使用。比如：官方 Debian 不能正确识别 HHKB 键盘，Mate 则可以。官方 Debian 的 Fcitx 有后选词列表变黑框的 BUG，Mate 则没有，甚至 Mate 的默认源里还有 Rime 输入法。
所以如果你想把树莓派 2 当作一台电脑使用，那么推荐安装 Ubuntu Mate。

- Ubuntu Mate Download: [[hhttps://ubuntu-mate.org/vivid]]

将 Ubuntu Mate 镜像写入 MiniSD 卡之后，第一次启动系统会进入安装配置步骤，可以选择系统语言，所在地，创建新的用户密码等等。安装大概需要十几分种，安装完成之后会自动进入桌面。

进入桌面之后首先重新分区 MiniSD 卡，使 Mate 可以使用全部 MiniSD 卡容量：

#+begin_src
sudo fdisk /dev/mmcblk0
#+end_src

删除第 2 个分区，按(d 2)，然后重新创建使用默认值，按(n p 2 回车 回车)，最后保存所有修改，按(w)，接着重启系统。

重启系统之后执行：

#+begin_src
sudo resize2fs /dev/mmcblk0p2
#+end_src

然后设置将主目录下的所有默认文件夹名称变为英语，方便在 Terminal 中输入：

#+begin_src
export LANG=en_US
xdg-user-dirs-gtk-update
#+end_src

在跳出的选框之中选择同意转化目录名称，之后在将默认值设置回中文：

#+begin_src
export LANG=zh_CN
#+end_src

接着安装字体：

#+begin_src
apt-cache search fonts | grep WenQuanYi
# 将所有显示出的 WenQuanYi 字体全部安装
#+end_src

安装 Source Code Pro 字体：

#+begin_src
wget https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.zip
unzip 1.030R-it.zip
mkdir -p ~/.fonts
cp source-code-pro-2.010R-ro-1.030R-it/OTF/*.otf ~/.fonts/
fc-cache -f -v
#+end_src

最后安装中文输入法：

- Rime

#+begin_src
sudo apt-get install ibus
sudo apt-get install ibus-rime
#+end_src

- Fcitx and Google 拼音

#+begin_src
sudo apt-get install fcitx
sudo apt-get install fcitx-googlepinyin
#+end_src

重新启动之后或重启 X-Window 后输入法就会启用。至此，Ubuntu Mate for Raspberry Pi2 的中文化设置就完成了。

FAQ：

如果你和我一样使用 1920x1080 的分辨率，用 HDMI 线链接默认没有全屏，则：

#+begin_src
sudo vim /boot/config.txt
#+end_src

找到以下行，删除前面的注释#：

#+begin_src
#disable_overscan=1
#+end_src

重新启动系统之后就会默认全屏。


